apiVersion: v1
kind: Namespace
metadata:
  name: velero
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: velero
type: Opaque
data:
 
  accesskey: bWluaW9hY2Nlc3M=     
  secretkey: bWluaW9zZWNyZXQ=      
